### ISSUE TITLE
Symbol TTF Not Working?

### ISSUE THREAD

**Issue by drewmiller** [RazrFalcon/ttf-parser#171]
Thanks for the great parser! It seems the below returns None in both instances although https://en.wikipedia.org/wiki/Symbol_(typeface) implies that it should yield indices for the "!" character. 

```rust
fn main() {
    let font_data = std::fs::read("C:/Windows/Fonts/symbol.ttf").unwrap();
    let face = ttf_parser::Face::parse(&font_data, 0).unwrap();
    println!("index: {:?}", face.glyph_index('\u{33}'));
    println!("index: {:?}", face.glyph_index('!'));
    return;
}
```

**Comment by RazrFalcon** [comment]
Can you try:

```rust
for subtable in face.tables().cmap.unwrap().subtables {
    println!(
        "Platform: {:?}, encoding: {}, is Unicode: {}",
        subtable.platform_id, subtable.encoding_id, subtable.is_unicode()
    );
}

`Face::glyph_index` supports only Unicode mapping.
```

**Comment by drewmiller** [comment]
Thanks @RazrFalcon  for the quick response! Here's what I've got.

```
Platform: Macintosh, encoding: 0, is Unicode: false
Platform: Windows, encoding: 0, is Unicode: false
```

Is there a way to modify the font to fix this issue? Appreciate any help you can give, and I'll also dig into it further myself. Thanks again.

**Comment by RazrFalcon** [comment]
What you have to do is to convert/map Unicode codepoints to Symbol-compatible codepoints. And then call [cmap::Subtable::glyph_index](https://docs.rs/ttf-parser/latest/ttf_parser/cmap/struct.Subtable.html#method.glyph_index)
I don't know what "encoding" the Symbol font uses and it's kinda out of `ttf-parser` scope.

Basically, `Face::glyph_index` maps a Unicode codepoint to a Glyph Index using font's `cmap` table. If a font doesn't have a Unicode `cmap` table then there is nothing to map. That's why you're getting `None`.
