### ISSUE TITLE
[CFF] OffSize value of zero used in tests is invalid

### ISSUE THREAD

**Issue by wezm** [RazrFalcon/ttf-parser#45]
Hi, I am working on porting `ttf-parser`'s CharString porting code to Allsorts. I noticed that in the CharString tests CFF fonts are built with an `OffSize` in the header of zero, which Allsorts rejects. This works in `ttf-parser` because [this value is skipped](https://github.com/RazrFalcon/ttf-parser/blob/439aaaebd50eb8aed66302e3c1b51fae047f85b2/src/tables/cff/cff1.rs#L123). The comment on that line (and in the tests) suggest that perhaps is value has been misinterpreted as it's not an absolute offset but the size in bytes of absolute offsets with valid values being 1–4.

This is what the CFF1 reference says:

<img src="https://user-images.githubusercontent.com/21787/104543013-b5238400-5678-11eb-9704-57f65070bba6.png" alt="Screenshot from 2021-01-14 13-47-48" width="580">

CFF2 says:

Name | Range | Description
-- | -- | --
OffSize | 1 to 4 | 1-byte unsigned number specifies the size of an Offset field or fields

Anyway not a huge issue since the value is unused but I thought I'd mention it anyway.

**Comment by RazrFalcon** [comment]
The reason why `ttf-parser` doesn't parse absolute offset, is because it's useless. [HarfBuzz](https://github.com/harfbuzz/harfbuzz/blob/c8c5e52aba904cfede1c7e8e1043a392053938e6/src/hb-ot-cff1-table.hh#L1394) and [FreeType](https://github.com/freetype/freetype2/blob/f9f6adb625c48ef15b5d61a3ac1709a068ea95a3/src/cff/cffload.c#L2244) ignore it too. In my experience, it always set to 3. I guess this is just an weird rudiment and the spec doesn't explain it properly.

**Comment by wezm** [comment]
Fair enough. Feel free to close.
