### ISSUE TITLE
Recursive_VF_1.070.ttf (variable) missing glyphs

### ISSUE THREAD

**Issue by alexheretic** [RazrFalcon/ttf-parser#48]
Font: https://github.com/arrowtype/recursive/releases/download/v1.070/ArrowType-Recursive-1.070.zip **Recursive_VF_1.070.ttf**

_font2svg_ example has many missing glyphs.

![](https://user-images.githubusercontent.com/2331607/104819766-9ca59c00-5827-11eb-8b06-f56b4166347c.png)

Is this font format not supported yet?

**Comment by RazrFalcon** [comment]
Yes, this is definitely a bug.

**Comment by RazrFalcon** [comment]
Because `ttf-parser` is zero-allocation, we have to limit _variation tuples_ to 16 while the technical limit is 4095. And this font uses 15-23. This is the reason.

I will increase the limit to 32. This should be good enough. 

PS: on older Rust versions I had a drastic performance regression when using larger tuples stack, but looks like it was fixed, because on 1.49 I don't see any performance differences.

**Comment by RazrFalcon** [comment]
I will publish a new release now, but note that a new version has variable fonts support as an optional feature. Afaik, you're using `--no-default-features`.

**Comment by alexheretic** [comment]
Thanks for looking into this & the heads up about the features :+1: I'll take a look at the feature activation up the stack.

**Comment by RazrFalcon** [comment]
Just to clarify even more, by disabling variable fonts support variable OpenType fonts (`CFF2`) will stop working (can be fixed in the future). Regular OpenType fonts (`CFF`) will continue working.
TrueType fonts (`glyf`) will work anyway and will be outlined using the default variation style (i.e. without applying the variation deltas).

Disabling variable fonts makes ttf-parser 2x smaller binary-wise and slightly faster in some operations.
