### ISSUE TITLE
bbox fallback regression in 0.12.2

### ISSUE THREAD

**Issue by alexheretic** [RazrFalcon/ttf-parser#61]
I have a regression test for #49 that's been broken by `0.12.2`.

For example for airstrip `GlyphId(89)`.

### 0.12.1
```rust
Rect {
    x_min: 0,
    y_min: -3,
    x_max: 1102,
    y_max: 1301,
}
```

### 0.12.2
```rust
Rect {
    x_min: 0,
    y_min: 0,
    x_max: 0,
    y_max: 0,
}
```

**Comment by RazrFalcon** [comment]
Well. Either way one of the fonts will be broken. The only solution I see is to ignore `glyf`'s table bbox completely and always use a calculated one.
I can't find any information about `glyf` bbox rules. Mainly what to do when the embedded bbox is not the same as the real/calculated one. Is this is a font generation error or expected behaviour. 

Just in case, here is FreeType bbox: `2,-1301 1102x1301` and Harfbuzz: `2,0 0x0`

PS: writing a proper test suite is my top priority, but this will take a lot of time and I don't have any...
