### ISSUE TITLE
[kern] Support subtable with format 2

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/ttf-parser#8]
https://docs.microsoft.com/en-us/typography/opentype/spec/kern#format-2

**Comment by madig** [comment]
Idle though: why support the legacy `kern` table? Any serious text layout software is going to use the OpenType features code in `GPOS` and maybe other specialised tables instead (see HarfBuzz), which is probably outside the scope of this package.

**Comment by RazrFalcon** [comment]
GSUB/GPOS are in scope and will be added later (they already implemented locally). And HarfBuzz fallback to `kern`, afaik, in some cases.

I plan to use this library in a text shaping library like HarfBuzz eventually.

**Comment by behdad** [comment]
Re `kern` legacy subtables formats, HarfBuzz implements those.

Regarding this project, I have my own reservations.  I fully support doing something like this in Rust properly.  But that would, IMO, involve using macros to place struct members automatically, in a way that would be superior to how HarfBuzz is done.  This project as is, is nothing close to that.  It's all manual offset parsing.  It's not scalable.

@SimonSapin has some work towards that, I don't remember where.  And there's the (rather annoying) YesLogic reimplementation of HarfBuzz in Rust that they say *will* be Open Source but currently isn't.

I like to see a HarfBuzz successor done in Rust.  I hate to see it repeat the same mistakes that HarfBuzz did early on and learn the hard way, when one can learn from HarfBuzz and improve on it.

**Comment by behdad** [comment]
cc @raphlinus

**Comment by raphlinus** [comment]
Simon's work is in [https://github.com/SimonSapin/victor/tree/master/victor/src/fonts](victor). It's good work.

Also what Behdad said about the various different efforts. It's going to be very difficult to coordinate the work (it often feels like herding cats), let alone get it anywhere near the level of polish that HarfBuzz has today. But there seems to be demand.

**Comment by RazrFalcon** [comment]
@behdad 

>involve using macros to place struct members automatically

Procedural macros?  So they will generate the parsing code automatically?

>It's not scalable.

What do you mean? Performance, cost of adding new tables, something else?

At the moment, all other Rust ttf/otf parsers I know are even worst, so it's at least something. But I would glad to hear any suggestions. Especially from a person who is familiar with this field. Before starting this project I had no experience in writing binary parsers and truetype specifically. So I do not expect much from it.

As for harfbuzz, I think that this is already a bit obvious that I'm working on a port too and spend like a month on it already. Right know I'm trying to do just a straightforward port, something that will produce the same output as harfbuzz. And then I plan to make it more Rustified.

**Comment by SimonSapin** [comment]
I’m guessing that by not scalable, Behdad means code like this that has hard-coded offsets like `8` and `34` here:

https://github.com/RazrFalcon/ttf-parser/blob/09228b7cbb4ed1a9e2be48a591d644d660991d93/src/hhea.rs#L30-L41

These constants sort of go against the “no magic numbers” stated goal of this crate.

My experiments with TrueType parsing are at:

* https://github.com/SimonSapin/victor/tree/fdb11f3e87f/victor/src/fonts
* https://github.com/SimonSapin/victor/blob/fdb11f3e87f/proc-macros/src/lib.rs

It’s not at all intended to be used directly by anyone else, but feel free to copy ideas or code if you like. The idea is to have struct definitions for each (portion of an) sfnt table like this:

```rust
#[derive(SfntTable)]
pub struct TableDirectoryEntry {
    tag: Tag,
    _checksum: u32,
    table_offset: u32,
    _length: u32,
}
```

No value of this type is ever created. Instead, the fields serve as input to a procedural macro that does the offset calculations, then generates code very similar to that of current `ttf-parser` (except not hard-coded).

----

As to complex shaping, I too would like to see it exist in Rust (whether a port or an alternative implementation). However I’m also worried about long-term maintenance: it’s ongoing work to keep porting future HarfBuzz improvements (where applicable).

**Comment by RazrFalcon** [comment]
@SimonSapin I do not consider this constants as magic numbers. By *magic numbers* I meant something like [this](https://gitlab.redox-os.org/redox-os/stb_truetype-rs/blob/master/src/lib.rs#L550) or [this](https://github.com/raphlinus/font-rs/blob/ad0b79ea9b76cc80687ad4363d4fa692fbd0ddf8/src/font.rs#L1054). `ttf-parse` doesn't have anything like this intentionally. 

As for procedural macros, I'm not keen to use them. It's hard to write and support them (I'm writing in Rust for 3 years now and I have no idea how to write proc-macros) and the compilation time penalty is enormous. Right now, it takes just 2sec to build `ttf-parser`, but it would take at least 30sec with proc-macros, because of `syn`.
Also, proc-macro should handle non-rust types, like u24 and optional fields that depend on a table version or some bit in a whole different table.

Also, I have a script that generates this offsets for me, but it's not published. It has necessary tables hardcoded and all you need is to run it:

```
~> ./offset.py vhea numOfLongVerMetrics
34
```

And since this offsets is not something that will be changed any time soon, it's no point in calculating them each time.

**Comment by SimonSapin** [comment]
Ok, magic number might not be the right term.

And yes, today’s procedural macros with today’s `syn` have their downside. It’s not about those specific tools though. I think the larger point is that code like the `line_gap` and `number_of_hmetrics` methods quoted/linked above should probably be auto-generated *somehow*, based on a concise definition that’s easy to write from the spec.

For example it could be a Python script (low compile / interpreter startup time) that generates Rust code instead of just integers, and generated code could be published with the crate so that users don’t need Python.

(For what it’s worth I have mixed feelings about my experience with generating Rust code from Python and [Mako templates](https://github.com/servo/servo/blob/ec1da1d01c0/components/style/properties/properties.mako.rs). That part of Servo/Stylo grew organically over the years and is one of the most hairy to maintain now.)

**Comment by SimonSapin** [comment]
> should probably be auto-generated

Anyway, this is my opinion and I think Behdad’s. I wanted to explain how it works in case you find it interesting.

It’s also true that DRY can be pushed too far, and sometimes complex meta-programming can be worse than a bit of copy-pasting and hard-coding. Whether the number of tables / fields in TrueType is high enough to make code generation worthwhile is debatable, and ultimately you decide what you prefer for your own projects.

**Comment by RazrFalcon** [comment]
I thinks that a python script that generates a Rust code is a better solution, but there are not that many places were you can apply it. OS/2, post, head, hhea, vhea and that's it. Everything else has way more complex algorithms than "get a data at offset".

One thing that would benefit from proc-macros in `ttf-parser` is `FromData` [generation](https://github.com/RazrFalcon/ttf-parser/blob/09228b7cbb4ed1a9e2be48a591d644d660991d93/src/name.rs#L199). Actually, this is how [goblin](https://crates.io/crates/goblin) works. They use [scroll](https://crates.io/crates/scroll) which is basically the same as `ttf-parser`'s `FromData`.

**Comment by behdad** [comment]
My concerns are the same as what Simon expressed.  I also just opened one of the tables to see how parsing is done, and came to same conclusions seeing eg this:

https://github.com/RazrFalcon/ttf-parser/blob/master/src/os2.rs#L240-L252

15 lines to pull out one number...  That's what's not scalable.  I suggest you watch the TYPO Labs 2018 presentation of mine which also touches on this subject:

https://www.youtube.com/watch?v=murPX2nfI9o
https://docs.google.com/presentation/d/1Hfglew_SGOVxEYcPRNO8XFAv8x_kOvcIKw25BexW_oU/edit

In short, we agree that parsing and loading into separate structs is wasteful.  I covered that here:

  http://goo.gl/woyty

There are two solutions left: 1. check access bounds every time (what ttf-parser does essentially), or check access bounds once, and access without check thereafter (what HarfBuzz does).  So, that's one parameter.

I've thought about generating code from Python as well.  But found it hard to weave that with custom code, which will inevitably be needed.  As such, my solution was to use C++ language facilities to get as close as an expressive DRY as I can get.  I'm really proud of how close I got to that.  Check how HarfBuzz's GSUB/GPOS are done.  Think about how you would do *that* table before settling on a design.  No, unlike what you said, it's not for just simple tables.  The two things that C++ currently doesn't allow (but a future version of the standard will, when Python-like metaclasses / Rust-like proc macros are added via the reflection and code-generation proposals):

  * Automatically handle offsets of struct members that are after a struct member with variable size,
  * Visitor pattern without enumerating members for each struct.

A few others who have tried to solve the same problem:
- https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/otData.py
- https://github.com/Pomax/A-binary-parser-generator (by @Pomax)
- https://github.com/foliojs/fontkit/tree/master/src/tables (by @devongovett)
- https://www.sweetscape.com/010editor/repository/files/OpenType.bt

**Comment by RazrFalcon** [comment]
Thanks. I will study those articles.

**Comment by behdad** [comment]
cc @adrianwong

**Comment by mikeday** [comment]
As @behdad mentioned, we are also working on OpenType font parsing in Rust at YesLogic, for use in our Prince typesetter. Our initial implementation is simple and hand-written, for example this is the code to parse a Coverage table from GSUB/GPOS:
```
pub enum Coverage<'a> {
    Format1 {
        glyph_array: ReadArray<'a, U16Be>,
    },
    Format2 {
        coverage_range_array: ReadArray<'a, CoverageRangeRecord>,
    },
}

pub struct CoverageRangeRecord {
    start_glyph: u16,
    end_glyph: u16,
    start_coverage_index: u16,
}

impl<'a> ReadFrom<'a> for CoverageRangeRecord {
    type ReadType = (U16Be, U16Be, U16Be);
    fn from((start_glyph, end_glyph, start_coverage_index): (u16, u16, u16)) -> Self {
        CoverageRangeRecord {
            start_glyph,
            end_glyph,
            start_coverage_index,
        }
    }
}

impl<'a> ReadBinary<'a> for Coverage<'a> {
    type HostType = Self;

    fn read(ctxt: &mut ReadCtxt<'a>) -> Result<Self, ParseError> {
        match ctxt.read_u16be()? {
            1 => {
                let glyph_count = ctxt.read_u16be()?;
                let glyph_array = ctxt.read_array::<U16Be>(usize::from(glyph_count))?;
                Ok(Coverage::Format1 { glyph_array })
            } 
            2 => {
                let coverage_range_count = ctxt.read_u16be()?;
                let coverage_range_array =
                    ctxt.read_array::<CoverageRangeRecord>(usize::from(coverage_range_count))?;
                Ok(Coverage::Format2 {
                    coverage_range_array,
                })
            } 
            _ => Err(ParseError::BadVersion),
        }
    }
}
```
You can see that we have various traits for reading binary data, and the ReadArray type stores a lazy reference into the original buffer that can be iterated over or indexed into on demand. The resulting code is easy to write based on the spec and performs reasonably well, although it will not be optimal for every use case.

In the longer term we would like to explore more powerful approaches than Rust macros or Python scripts for code generation (which we do use extensively in Prince!) and so we are also developing a Data Description Language based on dependent type theory with the intention of using it to specify _all_ of OpenType, including the difficult parts, and hopefully other binary formats as well.

Our work on the DDL in progress is available here https://github.com/yeslogic/ddl and includes many experiments dating back some years; it is not ready for production use! But we hope to begin introducing it to our font code in the near future. I would be happy to discuss this work in more detail if you are interested.

**Comment by brendanzab** [comment]
Really cool work on this @RazrFalcon! It’s nice to see more interest in OpenType parsing in Rust! We think that it’s worth experimenting with different approaches - binary format parsing is an interesting and tricky problem, and it’s worth thinking about it in different ways!

 I’ll have the slides from my [presentation at Compose Melbourne](http://www.composeconference.org/2019-melbourne/speakers/#brendan-zabarauskas) online soon. It was recorded, but it might take some time for it to be edited and uploaded - so I was working on getting my speaker notes online. In it I talk about the work I’ve been doing at YesLogic on binary format parsing - OpenType is our focus, but we’d also like to ultimately support more formats as well.

It’d be interesting to compare notes on our approaches, hopefully making our [DDL repository public](https://github.com/yeslogic/ddl) helps a bit. I’ve felt under pressure to do this for a long time, and it’s a relief to finally make it public! I hope this also provides more confidence that we will do the same for our shaping work too. As Mike says, the shaping code doesn’t currently use the DDL, but we are writing it in a way that will allow us to progressively migrate it in the future.

Here’s some of our previous experiments with describing OpenType declaratively:

- [experiments/mercury-prototype/ddl/opentype.ddl](https://github.com/yeslogic/ddl/blob/e8943178e1fc3e51378d908b41104ffc293a44ed/experiments/mercury-prototype/ddl/opentype.ddl)
- [rust-prototype-v2/tests/fixtures/opentype.ddl](https://github.com/yeslogic/ddl/blob/e8943178e1fc3e51378d908b41104ffc293a44ed/experiments/rust-prototype-v2/tests/fixtures/opentype.ddl)

We’ve learned a bit more since then, so this will change - for example we need to handle mutual recursion between the subtables. Hopefully this gives a feeling for the direction we are heading in though. You can also check out some of the [references](https://github.com/yeslogic/ddl/blob/e8943178e1fc3e51378d908b41104ffc293a44ed/docs/specification/references.md) we’ve been basing our work on. Looking at it now, I’m missing some, but it may give an idea what we are basing our work off.

When I first started at YesLogic I was originally interested in trying out an embedded DSL approach using procedural macros, but we’ve ultimately decided to go with an external DSL instead because we were hoping that this would allow us to use our work to improve our understanding OpenType. We’re also hoping for better type safety guarantees than we could have with Rust alone - for example statically verifying behaviour around integer overflows and array/offset bounds.

Definitely interested in checking out some of those links too @behdad, I’ve checked out how a number of projects have done parsing, including both Harfbuzz and FontKit. :)

**Comment by behdad** [comment]
Thanks for all the sharing and discussion. This is amazing. Looking forward to study those resources.

**Comment by behdad** [comment]
I don't know where to bookmark this issue so I can remember / find it later. :))

**Comment by madig** [comment]
![Bildschirmfoto 2019-10-01 um 20 08 52](https://user-images.githubusercontent.com/380829/65992582-605df900-e487-11e9-9fe5-c5a32c052023.png)
Note the bookmark icon.
